### ISSUE TITLE
Export doesn't work with any settings

### ISSUE THREAD

**Issue by edkashinsky** [audiokinetic/ReaWwise#3]
Hello! I'm trying to set up ReaWwise with my Macbook, I use wwise 2021.1.12 and Reaper 6.78 and OSX is Ventura 13.2.1

I repeated this tutorial https://blog.audiokinetic.com/en/reawwise-connecting-reaper-and-wwise/ but I get this error:
Transfer to Wwise Aborted
One or more files filed to render.

I'm sure that ReaWwise monitors wwise project structure correctly and shows tentative exported files metadata. Audio files are exported to a reaper project folder, but it doesn't transfer to wwise project sfx folder

I found log and I attach it here:
[Log_2023-03-22.txt](https://disk.yandex.ru/d/HXkGt459TFiEEA)

Could you help to fix it?

**Comment by theandrewcosta** [comment]
Hello @edkashinsky,

Can you confirm that REAPER actually renders files when you click "Transfer to Wwise"? Before transferring the files to Wwise, ReaWwise tells REAPER to render based off of the project render settings. After the render is complete, ReaWwise validates that the render was successful. If it doesn't detect any new files in the render directory, it aborts the transfer.

**Comment by ak-acosta** [comment]
Hello @edkashinsky,

Can you confirm that REAPER actually renders files when you click "Transfer to Wwise"? Before transferring the files to Wwise, ReaWwise tells REAPER to render based off of the project render settings. After the render is complete, ReaWwise validates that the render was successful. If it doesn't detect any new files in the render directory, it aborts the transfer.

**Comment by ak-acosta** [comment]
This is fixed in ReaWwise 1.0.5.
