### ISSUE TITLE
Type defs for lua API

### ISSUE THREAD

**Issue by AntoineBalaine** [audiokinetic/ReaWwise#4]
Hello,

I maintain the [reascript vscode extension](https://marketplace.visualstudio.com/items?itemName=AntoineBalaine.reascript-docs). It's used to provide type definitions when scripting on top of reaper.
 
Nick Von Kaenel just opened a [PR](https://github.com/AntoineBalaine/vscode-reascript-extension/pull/14) to include typedefs for reawwise.

Dunno if that's interesting to you in anyway, but I just thought I'd let you know.

**Comment by ak-pmaheux** [comment]
Hi Antoine,

**Comment by ak-pmaheux** [comment]
Hi Antoine,

Thanks for letting us know.
the reascript extension looks great, especially with the addition of the ReaWwise lua definitions.
This is an interesting and usefull addition even for us.
